### ISSUE TITLE
[가로 형식 맞추기] - 짧은 if문에도 { }를 써야 하는 이유?

### ISSUE THREAD

**Issue by deepredk** [Eighteeen/CleanCode_Book_Study#10]
if (visited[i]) continue;

책에서는 위와 같은 코드를

if (visited[i]) {
  continue;
}

이렇게 쓰라고 합니다.

근데 그에 대해서 부연설명은 따로 없더라고요. 제일 궁금했던 부분이었는데..

대신 저희가 직접 당위성을 붙여보는건 어떨까요?
아니면 그럴 필요가 없는 것 같다는 의견도 괜찮고요.

**Comment by deepredk** [comment]
간단하게 제 의견 남겨보자면

1. if문 안에 또 다른 코드를 추가로 넣게 될 경우를 고려하여
2. 계층 구조를 통일성있게 표현하기 위해

쓰는게 좋지 않을까 싶습니다

**Comment by sookyeonghwang** [comment]
저는 가독성이 높기 때문이라고 생각해요.
3장에서 

> 코드는 위에서 아래로 이야기처럼 읽혀야 좋다

라고 하였습니다. 위 말에 한 부분이지 않을까요?

**Comment by WinningBean** [comment]
__들여쓰기 무시하기__ 를 피하자는 부분에서 부연 설명이 되어 있는 것 같습니다.

> 때로는 간단한 if 문, 짧은 while 문, 짧은 함수에서 들여쓰기 규칙을 무시하고픈 유혹이 생긴다. 이런 유혹에 빠질 때마다 나는 항상 원점으로 돌아가 들여쓰기를 넣는다. 즉, 나는 다음과 같이 한 행에 범위를 뭉뚱그린 코드를 피한다.

> 들여쓰기로 범위를 제대로 표현한 코드를 선호한다.

위와 같은 맥락으로 일단 예시로 들어주신
```java
if (visited[i]) {
continue;
}
```

이 소스 부분을
```java
if (visited[i]) {
    continue;
}
```
이렇게 고쳐야 책에서 말하는 바와 동일한 규칙으로 이루어 지는 것 같네요.

**Comment by sookyeonghwang** [comment]
### 정리

1. 계층 구조를 통일하기 위해
2. 가독성이 높기 때문에
3. 들여쓰기 무시하기를 피하기 위해

위와 같은 이유로 짧은 if문에도 { }를 쓰는게 좋다.
