### ISSUE TITLE
[부수효과를 일으키지 마라!] - 시간적 결합과 순서 종속성에 대한 정확한 뜻

### ISSUE THREAD

**Issue by deepredk** [Eighteeen/CleanCode_Book_Study#6]
시간적 결합은 이미

- _( p. 55 )_ 시간적 결합(temporal coupling) : `메서드 A는 언제나 반드시 메서드 B보다 먼저 호출해야 한다.`와 같이 시간 순서에 따른 결합도를 말한다.

이렇게 설명이 되어있어서 저는 순서 종속성을 찾아봤는데

순서 종속성: 메서드들을 정해진 순서대로 실행해야 정상 작동 (출처: http://redutan.github.io/2016/07/01/cleancode-summary)
순서 종속성도 저것과 비슷한 의미로 나오더라고요

순서 종속성과 시간적 결합에 대한 정확한 뜻,
그리고 둘이 유사한 면이 있을 경우 둘의 차이가 궁금합니다

**Comment by sookyeonghwang** [comment]
**시간적 결합**은 어떤 식으로든 시간에 의존하는 일종의 결합입니다.
위에서 말했던 `메서드 A는 언제나 반드시 메서드 B보다 먼저 호출해야 한다.`처럼 메소드를 호출 하는 시간의 순서를 말하는 것도 맞지만 다른 경우도 시간적 결합이 있습니다.

시간이 지남에 따라 두가지 다른 형태의 시간적 결합으로 구분을 해보았습니다.

**1. 순서가 있는 경우(위와 같은 경우)**

한 일이 다른 일이 일어나기 전에 일어나야 한다.

**2. 기다려야 할 경우(대기 중)**

데이터베이스 쿼리나 RESTful API 호출 등과 같은 작업을 수행하는데  걸리는 시간을 말한다.  예를 들어, API를 호출해서 데이터를 가져 올 때 처럼 `대기시간`을 기다린 후에 작업을 해야한다.

**순서 종속성**은 말 그대로 순서에 종속됨으로써 정해진 순서대로 실행해야 한다는 의미가 가장 크다고 볼 수 있습니다.

-------------
즉 시간은 순서대로 흘러가는 것을 말하기 때문에 사실상 순서 종속성과 시간적 결합의 의미는 서로 매우 비슷하다고 생각합니다.

둘은 순서대로 실행한다는 점에서 유사하고 차이점을 굳이 뽑자면 **순서 종속성**에서는
`2. 대기 중`인 경우는 포함이 안된다는 점을 들 수 있을 것 같습니다.

**Comment by WinningBean** [comment]
**시간적 결합** : `메서드 A는 언제나 반드시 메서드 B보다 먼저 호출해야 한다.`이므로 A와 B를 하나씩 동시에 실행시킬 수 없게 됩니다.
-> 시간적으로 일들의 순서, 동시성의 역할

**순서 종속성** : 메서드 A 발생 후 B를 발생시킬 수만 있기 때문에 B 발생 후 A를 발생시킬 수 있는 상황에서는 쓰일 수 없는 함수이기 때문에 순서 종속성을 초래하게 됩니다.
-> 동작의 순서 연관성

**Comment by sookyeonghwang** [comment]
### 결론

**순서 종속성**은 **시간적 결합**에 포함되고 `대기 중`인 경우에 차이가 있다.
