### ISSUE TITLE
[결론] - '재귀라는 기교'의 정확한 뜻

### ISSUE THREAD

**Issue by WinningBean** [Eighteeen/CleanCode_Book_Study#8]
_p. 62_
> 시스템에서 발생하는 모든 동작을 설명하는 함수 계층이 바로 그 언어에 속한다.  
> 재귀라는 기교로 각 동작은 바로 그 도메인에 특화된 언어를 사용해 자신만의 이야기를 풀어간다.

위 문장에서 '**재귀라는 기교**'가 뜻하는 바를 정확히 알기 어려웠습니다.

저희가 흔히들 쓰는 '재귀 함수'라고 하기에는 문맥상 너무 뜬금없어서
정확히 알아보기 위해 사전적 의미를 찾아봤더니 '_본디의 곳으로 다시 돌아오는 것_' 이라고 하네요. (사전적 의미 찾아본 적 없었음)

그래서 앞 문장의 **함수 계층**과 관련하여,
함수 아래 계층에서 로직 수행 후 위 계층으로 다시 올라가기 때문에
재귀라는 표현을 사용했고,

또한 앞서서 알아봤던 내용들과 결합하여 생각하여,
함수 상단 계층(추상화 수준이 높은) 쪽은 문제 영역과 관련이 큰 이름들을 사용하기 때문에
'그 도메인에 특화된 언어'라는 표현을 썼구나.

이렇게 이해를 해보았는데, 여러분도 저와 동일하게 이해했을까요?
해당 문장을 어떻게 이해했는지 공유 해주세요!

**Comment by deepredk** [comment]
기교 = 함수를 잘 만들기 위한 기술
재귀 = 기교 중 한 예시

전 이렇게 이해했었어요.

**'프로그래밍 언어라는 수단을 사용해 좀 더 풍부하고 좀 더 표현력이 강한 언어를 만들어 이야기를 풀어간다'**
이 문장이 앞에 있는데
요것때문에 재귀라는 예시를 하나 든 것 같습니다.

저자가 '재귀라는 기교'라고도 했는데

**재귀'*라는*' 기교**
재귀가 기교 중 하나라고 하는 뜻이 간접적으로 내포돼있죠

**Comment by sookyeonghwang** [comment]
저는 @Winning-Bean 말처럼 이해했습니다.

`함수 아래 계층에서 로직 수행 후 위 계층으로 다시 올라가기 때문에
재귀라는 표현을 사용` 했다고 생각했습니다.

**Comment by sookyeonghwang** [comment]
### 결론

`재귀라는 기교`는 앞 문장의 함수 계층과 관련하여, 함수 아래 계층에서 로직 수행 후 위 계층으로 다시 올라가기 때문에 `재귀`라는 표현을 사용하였다.
