### ISSUE TITLE
[가로 형식 맞추기 - 가짜 범위] - 빈 while문, 빈 for문에서의 세미콜론

### ISSUE THREAD

**Issue by sookyeonghwang** [Eighteeen/CleanCode_Book_Study#9]
p. 113 에서
```
while(dis.read(buf, 0, readBufferSize) != 1)
;
```
처럼 코드를 작성하라고 하였습니다. while문 바로 옆에 세미콜론 붙이는 것은 while의 조건문을 실행하고 넘어가는 것으로 알고있습니다. 

세미콜론을 아래에다가 붙이는 것과 while문 바로 옆에 붙이는 것의 차이가 무엇인가요,,?

**Comment by deepredk** [comment]
코드 실행에는 당연히 아무런 차이가 없습니다.
'빈 while문임을 강조하기 위해 난 이렇게 한다'는 것 같습니다

**Comment by WinningBean** [comment]
@deepredk 의 의견과 동일하게 생각합니다.

**Comment by sookyeonghwang** [comment]
### 정리

빈 while문임을 강조하기 위해 사용한다.
